# Generated by Django 4.1 on 2023-06-02 18:12

from django.db import migrations, models
import django.db.models.deletion
import simplepro.components.fields
import simplepro.editor.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TransactionGeographyPoliticsCountryCollect",
            fields=[
                (
                    "ID",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="标识",
                    ),
                ),
                (
                    "CREATE_TIME",
                    simplepro.components.fields.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "UPDATE_TIME",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "STATUS_IS_DELETE",
                    models.BooleanField(default=False, verbose_name="逻辑删除"),
                ),
                (
                    "STATUS_IS_EFFECTIVE",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "NAME_CHINA",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=255, null=True, verbose_name="国家中文名称"
                    ),
                ),
                (
                    "NAME_ENGLISH",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=255, null=True, verbose_name="国家英文名称"
                    ),
                ),
                (
                    "CHINESE_ABBREVIATION",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=100, null=True, verbose_name="国家中文简称"
                    ),
                ),
                (
                    "ENGLISH_ABBREVIATION",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=100, null=True, verbose_name="国家英文简称"
                    ),
                ),
                (
                    "TWO_CHARACTER_CODE",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=100, null=True, verbose_name="国家两字符代码"
                    ),
                ),
                (
                    "THREE_CHARACTER_CODE",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=100, null=True, verbose_name="国家三字符代码"
                    ),
                ),
                (
                    "NUMERIC_CODE",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=100, null=True, verbose_name="国家数字代码"
                    ),
                ),
            ],
            options={
                "verbose_name": "国家基本信息",
                "verbose_name_plural": "国家基本信息",
                "db_table": "TransactionGeographyPoliticsCountryCollect",
                "ordering": ["-CREATE_TIME"],
            },
        ),
        migrations.CreateModel(
            name="TransactionGeographyPoliticsCountryCurrency",
            fields=[
                (
                    "ID",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="标识",
                    ),
                ),
                (
                    "CREATE_TIME",
                    simplepro.components.fields.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "UPDATE_TIME",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "STATUS_IS_DELETE",
                    models.BooleanField(default=False, verbose_name="逻辑删除"),
                ),
                (
                    "STATUS_IS_EFFECTIVE",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "COUNTRY_DESCRIBE_CHINESE",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=100, null=True, verbose_name="货币中文描述"
                    ),
                ),
                (
                    "COUNTRY_DESCRIBE_ENGLISH",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=100, null=True, verbose_name="货币英文描述"
                    ),
                ),
                (
                    "COUNTRY_NOTATION",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=100, null=True, verbose_name="货币符号"
                    ),
                ),
                (
                    "COUNTRY_ISO_CODE",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=100, null=True, verbose_name="ISO代码"
                    ),
                ),
                (
                    "COUNTRY_AUXILIARY_UNIT",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=100, null=True, verbose_name="辅助单位"
                    ),
                ),
                (
                    "COUNTRY_CARRY_SYSTEM",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=100, null=True, verbose_name="进位制"
                    ),
                ),
                (
                    "DETAIL",
                    simplepro.editor.fields.MDTextField(
                        blank=True, default=None, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "ID_NATION",
                    simplepro.components.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="country.transactiongeographypoliticscountrycollect",
                        verbose_name="国家",
                    ),
                ),
            ],
            options={
                "verbose_name": "国家货币",
                "verbose_name_plural": "国家货币",
                "db_table": "TransactionGeographyPoliticsCountryCurrency",
                "ordering": ["-CREATE_TIME"],
            },
        ),
    ]
