# Generated by Django 4.1 on 2023-06-02 18:12

from django.db import migrations, models
import simplepro.components.fields
import simplepro.editor.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TransactionSocialCultureEthnicPopulationEthnicClassificationCharacteristicsBrief",
            fields=[
                (
                    "ID",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="标识",
                    ),
                ),
                (
                    "CREATE_TIME",
                    simplepro.components.fields.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "UPDATE_TIME",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "STATUS_IS_DELETE",
                    models.BooleanField(default=False, verbose_name="逻辑删除"),
                ),
                (
                    "STATUS_IS_EFFECTIVE",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "NAME",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=127, null=True, verbose_name="名称"
                    ),
                ),
                (
                    "DETAIL",
                    simplepro.editor.fields.MDTextField(
                        blank=True, default="", null=True, verbose_name="简介"
                    ),
                ),
            ],
            options={
                "verbose_name": "民族基本信息",
                "verbose_name_plural": "民族基本信息",
                "db_table": "TransactionSocialCultureEthnicPopulationEthnicClassificationCharacteristicsBrief",
                "ordering": ["-CREATE_TIME"],
            },
        ),
    ]
