# Generated by Django 4.1 on 2023-06-02 18:12

from django.db import migrations, models
import django.db.models.deletion
import simplepro.components.fields
import simplepro.editor.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("standard_encoding", "0001_initial"),
        ("products", "0001_initial"),
        ("personal_Information", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProvenanceSystemFunctionPasswordRecords",
            fields=[
                (
                    "ID",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="标识",
                    ),
                ),
                (
                    "CREATE_TIME",
                    simplepro.components.fields.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "UPDATE_TIME",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "STATUS_IS_DELETE",
                    models.BooleanField(default=False, verbose_name="逻辑删除"),
                ),
                (
                    "STATUS_IS_EFFECTIVE",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "NUMBER",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=255, null=True, verbose_name="账号"
                    ),
                ),
                (
                    "PASSWORD",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=255, null=True, verbose_name="密码"
                    ),
                ),
                (
                    "DETAIL",
                    simplepro.editor.fields.MDTextField(
                        blank=True, default="", null=True, verbose_name="详情描述"
                    ),
                ),
                (
                    "ID_PERSON",
                    simplepro.components.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personal_Information.transactionsocialcultureethnicpopulationpersonalinformationperson",
                        verbose_name="记录人员",
                    ),
                ),
                (
                    "ID_PRODUCTS",
                    simplepro.components.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.transactioneconomyindustryproductsbasis",
                        verbose_name="产品",
                    ),
                ),
            ],
            options={
                "verbose_name": "人员密码",
                "verbose_name_plural": "人员密码",
                "db_table": "ProvenanceSystemFunctionPasswordRecords",
                "ordering": ["-CREATE_TIME"],
            },
        ),
        migrations.CreateModel(
            name="ProvenanceSystemFunctionPasswordCorrelation",
            fields=[
                (
                    "ID",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="标识",
                    ),
                ),
                (
                    "CREATE_TIME",
                    simplepro.components.fields.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "UPDATE_TIME",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "STATUS_IS_DELETE",
                    models.BooleanField(default=False, verbose_name="逻辑删除"),
                ),
                (
                    "STATUS_IS_EFFECTIVE",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "CODE",
                    simplepro.components.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="standard_encoding.provenancesystemsettingsstandardcodemaindict",
                        verbose_name="产品关联类别",
                    ),
                ),
                (
                    "ID_PASSWORD",
                    simplepro.components.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="产品账户",
                        to="password_records.provenancesystemfunctionpasswordrecords",
                        verbose_name="产品账户",
                    ),
                ),
                (
                    "ID_PASSWORD_RELATION",
                    simplepro.components.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="产品关联账户",
                        to="password_records.provenancesystemfunctionpasswordrecords",
                        verbose_name="产品账户",
                    ),
                ),
            ],
            options={
                "verbose_name": "产品账户关联",
                "verbose_name_plural": "产品账户关联",
                "db_table": "ProvenanceSystemFunctionPasswordCorrelation",
                "ordering": ["-CREATE_TIME"],
                "unique_together": {("ID_PASSWORD", "ID_PASSWORD_RELATION")},
            },
        ),
    ]
