version: '3'

services:
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./code:/code
      - ./static:/static
      - ./media:/media
      - ./logs:/logs
      - ./config:/config
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=True
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword

volumes:
  postgres_data: