# Generated by Django 4.1 on 2023-06-02 18:12

from django.db import migrations, models
import django.db.models.deletion
import simplepro.components.fields
import simplepro.editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProvenanceSystemSettingsStandardCodeMain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "DESCRIBE",
                    simplepro.components.fields.CharField(
                        db_index=True, max_length=255, unique=True, verbose_name="中文描述"
                    ),
                ),
                (
                    "TECHNOLOGY",
                    simplepro.components.fields.CharField(
                        db_index=True, max_length=255, unique=True, verbose_name="格式编码"
                    ),
                ),
            ],
            options={
                "verbose_name": "码表分类",
                "verbose_name_plural": "码表分类",
                "db_table": "ProvenanceSystemSettingsStandardCodeMain",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="ProvenanceSystemSettingsStandardContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "DESCRIBE",
                    simplepro.components.fields.CharField(
                        db_index=True, max_length=255, unique=True, verbose_name="中文描述"
                    ),
                ),
                (
                    "TECHNOLOGY",
                    simplepro.components.fields.CharField(
                        db_index=True, max_length=255, unique=True, verbose_name="格式编码"
                    ),
                ),
                (
                    "DETAIL",
                    simplepro.editor.fields.MDTextField(
                        blank=True, default=None, null=True, verbose_name="默认内容"
                    ),
                ),
            ],
            options={
                "verbose_name": "默认内容",
                "verbose_name_plural": "默认内容",
                "db_table": "ProvenanceSystemSettingsStandardContent",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="ProvenanceSystemSettingsStandardCodeMainDict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "TECHNOLOGY",
                    simplepro.components.fields.CharField(
                        db_index=True, max_length=255, verbose_name="格式编码"
                    ),
                ),
                (
                    "ABBREVIATION",
                    simplepro.components.fields.CharField(
                        max_length=100, verbose_name="中文描述"
                    ),
                ),
                (
                    "CODE_MAIN",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="分类",
                        to="standard_encoding.provenancesystemsettingsstandardcodemain",
                        to_field="TECHNOLOGY",
                        verbose_name="分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "码表详细",
                "verbose_name_plural": "码表详细",
                "db_table": "ProvenanceSystemSettingsStandardCodeMainDict",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="ProvenanceSystemSettingsStandardEncoding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "NAME_CHINESE",
                    simplepro.components.fields.CharField(
                        max_length=255, verbose_name="中文描述"
                    ),
                ),
                (
                    "NAME_ENGLISH",
                    simplepro.components.fields.CharField(
                        max_length=255, verbose_name="英文描述"
                    ),
                ),
                (
                    "ENCODING",
                    simplepro.components.fields.CharField(
                        db_index=True, max_length=16, verbose_name="标准格式编码"
                    ),
                ),
                (
                    "STATUS_IS_ENABLE",
                    models.BooleanField(default=False, verbose_name="是否启用"),
                ),
                (
                    "ID_PARENT",
                    simplepro.components.fields.TreeComboboxField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="standard_encoding.provenancesystemsettingsstandardencoding",
                        verbose_name="上级",
                    ),
                ),
            ],
            options={
                "verbose_name": "标准编码",
                "verbose_name_plural": "标准编码",
                "db_table": "ProvenanceSystemSettingsStandardEncoding",
                "ordering": ["-id"],
                "unique_together": {("ID_PARENT", "ENCODING")},
            },
        ),
    ]
