# Generated by Django 4.1 on 2023-06-02 18:12

from django.db import migrations, models
import django.db.models.deletion
import simplepro.components.fields
import simplepro.editor.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TransactionEconomyIndustryOrganizationsAddress",
            fields=[
                (
                    "ID",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="标识",
                    ),
                ),
                (
                    "CREATE_TIME",
                    simplepro.components.fields.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "UPDATE_TIME",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "STATUS_IS_DELETE",
                    models.BooleanField(default=False, verbose_name="逻辑删除"),
                ),
                (
                    "STATUS_IS_EFFECTIVE",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "ENTERPRISE_ADDRESS_NAME",
                    simplepro.components.fields.CharField(
                        max_length=255, verbose_name="地址"
                    ),
                ),
            ],
            options={
                "verbose_name": "组织地址信息",
                "verbose_name_plural": "组织地址信息",
                "db_table": "TransactionEconomyIndustryOrganizationsAddress",
                "ordering": ["-CREATE_TIME"],
            },
        ),
        migrations.CreateModel(
            name="TransactionEconomyIndustryOrganizationsBases",
            fields=[
                (
                    "ID",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="标识",
                    ),
                ),
                (
                    "CREATE_TIME",
                    simplepro.components.fields.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "UPDATE_TIME",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "STATUS_IS_DELETE",
                    models.BooleanField(default=False, verbose_name="逻辑删除"),
                ),
                (
                    "STATUS_IS_EFFECTIVE",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "ENTERPRISE_NAME",
                    simplepro.components.fields.CharField(
                        max_length=255, verbose_name="组织名称"
                    ),
                ),
                (
                    "COUNTRY_CREATE_TIME",
                    simplepro.components.fields.DateField(
                        blank=True, default="2023-06-02", null=True, verbose_name="成立时间"
                    ),
                ),
                (
                    "COUNTRY_END_TIME",
                    simplepro.components.fields.DateField(
                        blank=True, default="2023-06-02", null=True, verbose_name="结束时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "组织基本信息",
                "verbose_name_plural": "组织基本信息",
                "db_table": "TransactionEconomyIndustryOrganizationsBases",
                "ordering": ["-CREATE_TIME"],
            },
        ),
        migrations.CreateModel(
            name="TransactionEconomyIndustryOrganizationsCall",
            fields=[
                (
                    "ID",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="标识",
                    ),
                ),
                (
                    "CREATE_TIME",
                    simplepro.components.fields.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "UPDATE_TIME",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "STATUS_IS_DELETE",
                    models.BooleanField(default=False, verbose_name="逻辑删除"),
                ),
                (
                    "STATUS_IS_EFFECTIVE",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "ENTERPRISE_NAME",
                    simplepro.components.fields.CharField(
                        max_length=255, verbose_name="名称"
                    ),
                ),
            ],
            options={
                "verbose_name": "组织称呼信息",
                "verbose_name_plural": "组织称呼信息",
                "db_table": "TransactionEconomyIndustryOrganizationsCall",
                "ordering": ["-CREATE_TIME"],
            },
        ),
        migrations.CreateModel(
            name="TransactionEconomyIndustryOrganizationsCertificate",
            fields=[
                (
                    "ID",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="标识",
                    ),
                ),
                (
                    "CREATE_TIME",
                    simplepro.components.fields.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "UPDATE_TIME",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "STATUS_IS_DELETE",
                    models.BooleanField(default=False, verbose_name="逻辑删除"),
                ),
                (
                    "STATUS_IS_EFFECTIVE",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "DATE_ISSUED",
                    simplepro.components.fields.DateField(
                        blank=True,
                        default="2023-06-02 18:12:26",
                        null=True,
                        verbose_name="签发日期",
                    ),
                ),
                (
                    "NUMBER",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=255, null=True, verbose_name="组织证件号"
                    ),
                ),
                (
                    "DATE_START",
                    simplepro.components.fields.DateField(
                        blank=True,
                        default="2023-06-02 18:12:26",
                        null=True,
                        verbose_name="组织证件号有效开始日期",
                    ),
                ),
                (
                    "DATE_END",
                    simplepro.components.fields.DateField(
                        blank=True,
                        default="2023-06-02 18:12:26",
                        null=True,
                        verbose_name="组织证件号有效结束日期",
                    ),
                ),
            ],
            options={
                "verbose_name": "组织证件信息",
                "verbose_name_plural": "组织证件信息",
                "db_table": "TransactionEconomyIndustryOrganizationsCertificate",
                "ordering": ["-CREATE_TIME"],
            },
        ),
        migrations.CreateModel(
            name="TransactionEconomyIndustryOrganizationsDetails",
            fields=[
                (
                    "ID",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="标识",
                    ),
                ),
                (
                    "CREATE_TIME",
                    simplepro.components.fields.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "UPDATE_TIME",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "STATUS_IS_DELETE",
                    models.BooleanField(default=False, verbose_name="逻辑删除"),
                ),
                (
                    "STATUS_IS_EFFECTIVE",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "DETAIL",
                    simplepro.editor.fields.MDTextField(
                        blank=True, default="", null=True, verbose_name="详情描述"
                    ),
                ),
                (
                    "ID_ORGANIZATIONS",
                    simplepro.components.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.transactioneconomyindustryorganizationsbases",
                        verbose_name="组织",
                    ),
                ),
            ],
            options={
                "verbose_name": "组织详情描述",
                "verbose_name_plural": "组织详情描述",
                "db_table": "TransactionEconomyIndustryOrganizationsDetails",
                "ordering": ["-CREATE_TIME"],
            },
        ),
        migrations.CreateModel(
            name="TransactionEconomyIndustryOrganizationsContact",
            fields=[
                (
                    "ID",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="标识",
                    ),
                ),
                (
                    "CREATE_TIME",
                    simplepro.components.fields.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "UPDATE_TIME",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "STATUS_IS_DELETE",
                    models.BooleanField(default=False, verbose_name="逻辑删除"),
                ),
                (
                    "STATUS_IS_EFFECTIVE",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "NUMBER",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=255, null=True, verbose_name="编号"
                    ),
                ),
                (
                    "ID_ORGANIZATIONS",
                    simplepro.components.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.transactioneconomyindustryorganizationsbases",
                        verbose_name="组织",
                    ),
                ),
            ],
            options={
                "verbose_name": "组织联系表方式",
                "verbose_name_plural": "组织联系表方式",
                "db_table": "TransactionEconomyIndustryOrganizationsContact",
                "ordering": ["-CREATE_TIME"],
            },
        ),
    ]
