# Generated by Django 4.1 on 2023-06-02 18:12

from django.db import migrations
import django.db.models.deletion
import simplepro.components.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        ("standard_encoding", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactioneconomyindustryorganizationscontact",
            name="ID_PRODUCTS",
            field=simplepro.components.fields.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.transactioneconomyindustryproductsbasis",
                verbose_name="产品",
            ),
        ),
        migrations.AddField(
            model_name="transactioneconomyindustryorganizationscertificate",
            name="CODE",
            field=simplepro.components.fields.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="standard_encoding.provenancesystemsettingsstandardcodemaindict",
                verbose_name="组织证件类别",
            ),
        ),
        migrations.AddField(
            model_name="transactioneconomyindustryorganizationscertificate",
            name="ID_ORGANIZATIONS",
            field=simplepro.components.fields.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="组织",
                to="organizations.transactioneconomyindustryorganizationsbases",
                verbose_name="组织",
            ),
        ),
        migrations.AddField(
            model_name="transactioneconomyindustryorganizationscertificate",
            name="SIGNING_AND_ISSUING_ORGANIZATION",
            field=simplepro.components.fields.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="签发机关",
                to="organizations.transactioneconomyindustryorganizationsbases",
                verbose_name="签发机关",
            ),
        ),
        migrations.AddField(
            model_name="transactioneconomyindustryorganizationscall",
            name="ENTERPRISE_NAME_CODE",
            field=simplepro.components.fields.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="standard_encoding.provenancesystemsettingsstandardcodemaindict",
                verbose_name="组织称呼类型",
            ),
        ),
        migrations.AddField(
            model_name="transactioneconomyindustryorganizationscall",
            name="ID_ORGANIZATIONS",
            field=simplepro.components.fields.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.transactioneconomyindustryorganizationsbases",
                verbose_name="组织",
            ),
        ),
        migrations.AddField(
            model_name="transactioneconomyindustryorganizationsbases",
            name="ENTERPRISE_CODE",
            field=simplepro.components.fields.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="standard_encoding.provenancesystemsettingsstandardcodemaindict",
                verbose_name="组织类别",
            ),
        ),
        migrations.AddField(
            model_name="transactioneconomyindustryorganizationsaddress",
            name="ENTERPRISE_ADDRESS_CODE",
            field=simplepro.components.fields.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="standard_encoding.provenancesystemsettingsstandardcodemaindict",
                verbose_name="组织地址类型",
            ),
        ),
        migrations.AddField(
            model_name="transactioneconomyindustryorganizationsaddress",
            name="ID_ORGANIZATIONS",
            field=simplepro.components.fields.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.transactioneconomyindustryorganizationsbases",
                verbose_name="组织",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="transactioneconomyindustryorganizationsdetails",
            unique_together={("ID_ORGANIZATIONS",)},
        ),
        migrations.AlterUniqueTogether(
            name="transactioneconomyindustryorganizationscontact",
            unique_together={("ID_ORGANIZATIONS", "ID_PRODUCTS", "NUMBER")},
        ),
        migrations.AlterUniqueTogether(
            name="transactioneconomyindustryorganizationscertificate",
            unique_together={("ID_ORGANIZATIONS", "NUMBER")},
        ),
        migrations.AlterUniqueTogether(
            name="transactioneconomyindustryorganizationscall",
            unique_together={
                ("ID_ORGANIZATIONS", "ENTERPRISE_NAME_CODE", "ENTERPRISE_NAME")
            },
        ),
        migrations.AlterUniqueTogether(
            name="transactioneconomyindustryorganizationsbases",
            unique_together={("ENTERPRISE_NAME", "ENTERPRISE_CODE")},
        ),
        migrations.AlterUniqueTogether(
            name="transactioneconomyindustryorganizationsaddress",
            unique_together={
                (
                    "ID_ORGANIZATIONS",
                    "ENTERPRISE_ADDRESS_CODE",
                    "ENTERPRISE_ADDRESS_NAME",
                )
            },
        ),
    ]
