# Generated by Django 4.1 on 2023-06-02 18:12

from django.db import migrations, models
import django.db.models.deletion
import simplepro.components.fields
import simplepro.editor.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("standard_encoding", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProvenanceSystemFunctionDailyRecordsDiary",
            fields=[
                (
                    "ID",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="标识",
                    ),
                ),
                (
                    "CREATE_TIME",
                    simplepro.components.fields.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "UPDATE_TIME",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "STATUS_IS_DELETE",
                    models.BooleanField(default=False, verbose_name="逻辑删除"),
                ),
                (
                    "STATUS_IS_EFFECTIVE",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "DATE",
                    simplepro.components.fields.DateField(
                        blank=True,
                        default="2023-06-02 18:12:26",
                        null=True,
                        verbose_name="日期",
                    ),
                ),
                (
                    "DETAIL",
                    simplepro.editor.fields.MDTextField(
                        blank=True, default="", null=True, verbose_name="详情描述"
                    ),
                ),
            ],
            options={
                "verbose_name": "日记本",
                "verbose_name_plural": "日记本",
                "db_table": "ProvenanceSystemFunctionDailyRecordsDiary",
                "ordering": ["-DATE"],
            },
        ),
        migrations.CreateModel(
            name="ProvenanceSystemFunctionDailyRecordsEvent",
            fields=[
                (
                    "ID",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="标识",
                    ),
                ),
                (
                    "CREATE_TIME",
                    simplepro.components.fields.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "UPDATE_TIME",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "STATUS_IS_DELETE",
                    models.BooleanField(default=False, verbose_name="逻辑删除"),
                ),
                (
                    "STATUS_IS_EFFECTIVE",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "DATE",
                    simplepro.components.fields.DateField(
                        blank=True,
                        default="2023-06-02 18:12:26",
                        null=True,
                        verbose_name="发生日期",
                    ),
                ),
                (
                    "NAME",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=255, null=True, verbose_name="事件名称"
                    ),
                ),
                (
                    "DETAIL",
                    simplepro.editor.fields.MDTextField(
                        blank=True, default="", null=True, verbose_name="详情描述"
                    ),
                ),
                (
                    "IDENTITY",
                    simplepro.components.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="standard_encoding.provenancesystemsettingsstandardcodemaindict",
                        verbose_name="参与身份",
                    ),
                ),
            ],
            options={
                "verbose_name": "事件记录",
                "verbose_name_plural": "事件记录",
                "db_table": "ProvenanceSystemFunctionDailyRecordsEvent",
                "ordering": ["-DATE"],
            },
        ),
        migrations.CreateModel(
            name="ProvenanceSystemFunctionDailyRecordsEventType",
            fields=[
                (
                    "ID",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="标识",
                    ),
                ),
                (
                    "CREATE_TIME",
                    simplepro.components.fields.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "UPDATE_TIME",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "STATUS_IS_DELETE",
                    models.BooleanField(default=False, verbose_name="逻辑删除"),
                ),
                (
                    "STATUS_IS_EFFECTIVE",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "CODE",
                    simplepro.components.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="standard_encoding.provenancesystemsettingsstandardcodemaindict",
                        verbose_name="事件类型",
                    ),
                ),
                (
                    "ID_EVENT",
                    simplepro.components.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="daily_records.provenancesystemfunctiondailyrecordsevent",
                        verbose_name="事件",
                    ),
                ),
            ],
            options={
                "verbose_name": "事件类型",
                "verbose_name_plural": "事件类型",
                "db_table": "ProvenanceSystemFunctionDailyRecordsEventType",
                "ordering": ["-CREATE_TIME"],
            },
        ),
    ]
