# Generated by Django 4.1 on 2023-06-02 20:16

from django.db import migrations
import simplepro.components.fields


class Migration(migrations.Migration):

    dependencies = [
        ("daily_records", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provenancesystemfunctiondailyrecordsdiary",
            name="DATE",
            field=simplepro.components.fields.DateField(
                blank=True, default="2023-06-02 20:16:02", null=True, verbose_name="日期"
            ),
        ),
        migrations.AlterField(
            model_name="provenancesystemfunctiondailyrecordsevent",
            name="DATE",
            field=simplepro.components.fields.DateField(
                blank=True,
                default="2023-06-02 20:16:02",
                null=True,
                verbose_name="发生日期",
            ),
        ),
    ]
