version: '3'

services:
  python-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8022:22"
    volumes:
      - /Users/Shared/program/docker/entirely/entirely-python:/entirely  # Change the path to your actual code directory on host
    working_dir: /entirely
