"""
Django settings for entirely project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
import sys
from pathlib import Path

from docs.utils.system_communal.configuration import (
    SECRET_KEY__, IP_ADD_STRING__, Web_FRAME_OPTIONS, ZDY_APP_LIST, ZDY_MIDDLEWARES, MYSQL_ENGINE,
    STATIC_URL_NOT_ZDY_BZ, STATIC_URL_NOT_ZDY, ADMIN_URL_ZDY, MEDITOR_DEFAULT_CONFIG, UEDITOR_DEFAULT_CONFIG,
    APPLICATIONS_PATH
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BASE_DIR))
range_index = 1
for i in APPLICATIONS_PATH:
    sys.path.insert(range_index, str(BASE_DIR / i))
    range_index += 1
del range_index

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = SECRET_KEY__

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = IP_ADD_STRING__
X_FRAME_OPTIONS = Web_FRAME_OPTIONS[1]  # FRAME
APPEND_SLASH = True  # url是否会添加'\'

AUTH_USER_MODEL = 'account_management.ProvenanceSystemSettingsAccountManagementSuper'  # 用户model
# LOGIN_URL = 'account_management:ProvenanceSystemSettingsAccountManagementSuperAdmin'  # 权限认证Mixin

# Application definition

INSTALLED_APPS = [
    'simplepro',
    'simpleui',
    'import_export',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
]
if isinstance(ZDY_APP_LIST, list) and ZDY_APP_LIST:
    INSTALLED_APPS.extend(ZDY_APP_LIST)

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # 跨域请求
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "corsheaders.middleware.CorsPostCsrfMiddleware",  # 跨域请求
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]
if isinstance(ZDY_MIDDLEWARES, list) and ZDY_MIDDLEWARES:
    MIDDLEWARE.extend(ZDY_MIDDLEWARES)

ROOT_URLCONF = "entirely.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'docs/templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.media",  # 新增
            ],
        },
    },
]

WSGI_APPLICATION = "entirely.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
    # "default": {
    #     # 'django.db.backends.mysql', mysql.connector.django, django.db.backends.sqlite3,
    #     "ENGINE": "django.db.backends.mysql",
    #     "NAME": "Django1",
    #     'USER': 'root',
    #     'PASSWORD': 'li19990929..',
    #     'HOST': '0.0.0.0',
    #     'PORT': '3306',
    # }
}
# DATABASES_MYSQL = OperationMysqlData(MYSQL_ENGINE)
# DATABASES_MYSQL_CONN, DATABASES_MYSQL_CURSOR = DATABASES_MYSQL.context()

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://0.0.0.0:6379/0",  # 客户端
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",  # 自己的连接池子类
            "CONNECTION_POOL_KWARGS": {"max_connections": 100},  # 配置默认连接池
            "PASSWORD": "my_secret",  # password not in rul
            "PARSER_CLASS": "redis.connection.HiredisParser",  # 可扩展解析器
        }
    },
    'session': {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://0.0.0.0:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",  # 自己的连接池子类
        }
    },
    'verify_code': {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://0.0.0.0:6379/2",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",  # 自己的连接池子类
        }
    },
}

# 缓存设置global_settings
# https://docs.djangoproject.com/en/2.2/topics/http/sessions/#using-cached-sessions
# 详解[django文档](https://docs.djangoproject.com/en/2.2/ref/csrf/#acquiring-the-token-if-csrf-use-sessions-and-csrf-cookie-httponly-are-false)
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'session'
SESSION_COOKIE_AGE = 3600  # Session的cookie失效日期（2周）（数字为秒数）（默认）
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # 是否关闭浏览器使得Session过期（默认）
SESSION_SAVE_EVERY_REQUEST = True  # 是否每次请求都保存Session，默认修改之后才保存（默认）

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

if DEBUG:
    LANGUAGE_CODE = 'zh-hans'
    TIME_ZONE = 'Asia/Shanghai'
    STATIC_URL = STATIC_URL_NOT_ZDY_BZ
    STATICFILES_DIRS = [
        # os.path.join(BASE_DIR, STATIC_URL_NOT_ZDY),
        os.path.join(BASE_DIR, 'docs/static')
        # os.path.join(BASE_DIR, 'Applications', 'Bases', 'static'),
    ]

else:
    LANGUAGE_CODE = "en-us"
    TIME_ZONE = "UTC"
    STATIC_URL = STATIC_URL_NOT_ZDY_BZ
    # STATIC_ROOT = os.path.join(BASE_DIR, STATIC_URL_NOT_ZDY)
    STATIC_ROOT = os.path.join(BASE_DIR, 'docs/static')

USE_I18N = True
USE_L10N = True
USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

# STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# 上传文件，如果是ImageField字段，simplepro将默认显示为图片，但是请保证有MEDIA_URL字段，否则图片将会404无法显示
# urls.py 中需要加入:+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# 参考文章地址：https://www.cnblogs.com/ohahastudy/p/11179493.html
# demo 是全部已经配置好了的。
# Simplepro显示图片原理, <img src='img.url'> 将会直接读取django给到的url地址，所以不管是用本地，或者第三方的oss，都是可以的。
MEDIA_ROOT = os.path.join(BASE_DIR, 'docs/media/images')  # docs/media/images/mbHjR4S3.png
MEDIA_URL = '/docs/media/images/'  # http://127.0.0.1:8002/docs/media/images/sbhH9s9e.JPG
# http://127.0.0.1:8002/docs/static/images/favicon.svg

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

# UUIDField(primary_key=True, auto_created=True, default=uuid.uuid4, editable=False)
# DEFAULT_AUTO_FIELD = 'django.db.models.UUIDField'  # 不可以，只能在model使用
# 处理首页，通过设置判断打开的是默认页还是自定义的页面
# SIMPLEUI_HOME_PAGE = 'http://127.0.0.1:8001/'
# SIMPLEUI_HOME_TITLE = '小李的窝'
# https://fontawesome.com/icons/magnifying-glass?s=solid&f=classic
SIMPLEUI_HOME_ICON = 'fa fa-user'
# 登录页粒子动画，默认开启，False关闭
# SIMPLEUI_LOGIN_PARTICLES = False
# 让simpleui 不要收集相关信息
SIMPLEUI_ANALYSIS = True
# 首页监控图表显示和隐藏
# SIMPLEPRO_MONIT_DISPLAY = True  # True显示 False隐藏
# 收藏夹\网页小图标 将下载好的图标放入到项目的static目录中，然后取名为favicon.ico
# path('favicon.ico', RedirectView.as_view(url=r'/docs/static/images/favicon.ico')),
# http://127.0.0.1:8001/docs/static/images/favicon.svg
# 是否显示默认图标，默认=True
# SIMPLEUI_DEFAULT_ICON = False
# 图标设置，图标参考：
# SIMPLEUI_ICON = {
#     '系统管理': 'fab fa-apple',
#     '员工管理': 'fas fa-user-tie'
# }
# 指定simpleui 是否以脱机模式加载静态资源，为True的时候将默认从本地读取所有资源，即使没有联网一样可以。适合内网项目
# 不填该项或者为False的时候，默认从第三方的cdn获取
SIMPLEUI_STATIC_OFFLINE = True
# 隐藏所有simpleui和simplepro相关的信息 （版本和授权信息）
SIMPLEPRO_INFO = False
# 配置Simple Pro是否显示首页的图标，默认为True，显示图表，False不显示
SIMPLEPRO_CHART_DISPLAY = False
# 配置是否显示监控图表
SIMPLEPRO_MONIT_DISPLAY = True
# AUTH_USER_MODEL = 'simplepro.AuthUser'
# 默认主题
# SIMPLEUI_DEFAULT_THEME = 'dark.css'
# SIMPLEUI_LOGO='https://simpleui.72wo.com/static/images/pro/icon3.png'
SIMPLEUI_LOGO_LOGIN = '/null_svg'
# SIMPLEUI_LOGO = '/admin_png'
SIMPLEUI_LOGO = '/docs/static/images/19990929.jpg'
# SIMPLEUI_LOGO_LOGIN = ''
# SIMPLEUI_DEFAULT_THEME = 'pro.css'  # 使用旧版的界面样式
# 跨域请求
CORS_ALLOW_CREDENTIALS = True  # 允许携带cookie
CORS_ORIGIN_ALLOW_ALL = True  # 允许所有源访问
CORS_URLS_REGEX = r'^.*$'  # 限制发送CORS标头的URL的正则表达式。默认为r'^.*$'，即匹配所有URL的。
CSRF_TRUSTED_ORIGINS = ["https://i3855i1425.oicp.vip"]
CORS_ORIGIN_WHITELIST = (
    'http://127.0.0.1:8001', 'http://127.0.0.1:8080', 'http://localhost:8001', 'http://localhost:8080',
    "https://i3855i1425.oicp.vip",
)
CORS_ALLOW_METHODS = ('DELETE', 'GET', 'OPTIONS', 'PATCH', 'POST', 'PUT', 'VIEW',)  # 允许的方法
CORS_ALLOW_HEADERS = ('*',)  # 允许所有的请求头
# CORS_ALLOW_HEADERS = ('XMLHttpRequest', 'X_FILENAME', 'accept-encoding', 'authorization', 'content-type', 'dnt',
#                       'origin', 'user-agent', 'x-csrftoken', 'x-requested-with', 'Pragma',)  # 允许的请求头
# CSRF_TRUSTED_ORIGINS = ["http://change.allowed.com",]

SIMPLEPRO_FK_ASYNC_DATA = True

SIMPLEUI_CONFIG = {
    'system_keep': False,  # 在自定义菜单的基础上保留系统模块
    'dynamic': True,  # 开启动态菜单功能
    'menus': [
        {
            'name': '起源域',
            'icon': 'fa fa-file',  # 'far fa-surprise',
            'codename': 'provenance',
            'models': [
                {
                    'name': '系统设置',
                    'codename': 'system_settings',
                    'models': [
                        {
                            'name': '标准编码',
                            'codename': 'standard_encoding',
                            'models': [
                                {
                                    'name': '标准编码',
                                    'codename': 'ProvenanceSystemSettingsStandardEncoding',
                                    'url': f'/{ADMIN_URL_ZDY}standard_encoding/provenancesystemsettingsstandardencoding/'
                                },
                                {
                                    'name': '码表分类',
                                    'codename': 'ProvenanceSystemSettingsStandardCodeMain',
                                    'url': f'/{ADMIN_URL_ZDY}standard_encoding/provenancesystemsettingsstandardcodemain/'
                                },
                                {
                                    'name': '码表详情',
                                    'codename': 'ProvenanceSystemSettingsStandardCodeMainDict',
                                    'url': f'/{ADMIN_URL_ZDY}standard_encoding/provenancesystemsettingsstandardcodemaindict/'
                                },
                                {
                                    'name': '默认内容',
                                    'codename': 'ProvenanceSystemSettingsStandardContent',
                                    'url': f'/{ADMIN_URL_ZDY}standard_encoding/provenancesystemsettingsstandardcontent/'
                                }
                            ]
                        },
                        {
                            'name': '用户管理',
                            'codename': 'account_management',
                            'models': [
                                {
                                    'name': '订阅用户',
                                    'codename': 'account_management_A0',
                                    'models': [
                                        {
                                            'name': '超级管理',
                                            'codename': 'ProvenanceSystemSettingsAccountManagementSuper',
                                            'url': f'/{ADMIN_URL_ZDY}account_management/provenancesystemsettingsaccountmanagementsuper/'
                                        },
                                        {
                                            'name': '订阅用户',
                                            'codename': 'ProvenanceSystemSettingsAccountManagementSubscriber',
                                            'url': f'/{ADMIN_URL_ZDY}account_management/provenancesystemsettingsaccountmanagementsubscriber/'
                                        },
                                        {
                                            'name': '关联登陆',
                                            'codename': 'ProvenanceSystemSettingsAccountManagementSubscriberLand',
                                            'url': f'/{ADMIN_URL_ZDY}account_management/provenancesystemsettingsaccountmanagementsubscriberland/'
                                        }
                                    ]
                                },
                                {
                                    'name': '订阅用户组',
                                    'codename': 'account_management_A1',
                                    'models': [
                                        {
                                            'name': '用户组',
                                            'codename': 'ProvenanceSystemSettingsAccountManagementSubscriberGroup',
                                            'url': f'/{ADMIN_URL_ZDY}account_management/provenancesystemsettingsaccountmanagementsubscribergroup/'
                                        },
                                        {
                                            'name': '订阅用户组',
                                            'codename': 'ProvenanceSystemSettingsAccountManagementSubscriberGroupAccount',
                                            'url': f'/{ADMIN_URL_ZDY}account_management/provenancesystemsettingsaccountmanagementsubscribergroupaccount/'
                                        }
                                    ]
                                },
                                {
                                    'name': '角色管理',
                                    'codename': 'account_management_A1',
                                    'models': [
                                        {
                                            'name': '角色管理',
                                            'codename': 'ProvenanceSystemSettingsAccountManagementRole',
                                            'url': f'/{ADMIN_URL_ZDY}account_management/provenancesystemsettingsaccountmanagementrole/'
                                        },
                                        {
                                            'name': '用户角色',
                                            'codename': 'ProvenanceSystemSettingsAccountManagementRoleSubscriber',
                                            'url': f'/{ADMIN_URL_ZDY}account_management/provenancesystemsettingsaccountmanagementrolesubscriber/'
                                        },
                                        {
                                            'name': '用户组角色',
                                            'codename': 'ProvenanceSystemSettingsAccountManagementRoleSubscriberGroup',
                                            'url': f'/{ADMIN_URL_ZDY}account_management/provenancesystemsettingsaccountmanagementrolesubscribergroup/'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            'name': '菜单管理',
                            'codename': 'menu_management',
                            'models': [
                                {
                                    'name': '菜单管理',
                                    'codename': 'ProvenanceSystemSettingsMenuManagementMenu',
                                    'url': f'/{ADMIN_URL_ZDY}menu_management/provenancesystemsettingsmenumanagementmenu/'
                                },
                                {
                                    'name': '菜单参数',
                                    'codename': 'ProvenanceSystemSettingsMenuManagementMenuParameter',
                                    'url': f'/{ADMIN_URL_ZDY}menu_management/provenancesystemsettingsmenumanagementmenuparameter/'
                                },
                                {
                                    'name': '菜单展示',
                                    'codename': 'ProvenanceSystemSettingsMenuManagementMenuRoleDisplay',
                                    'url': f'/{ADMIN_URL_ZDY}menu_management/provenancesystemsettingsmenumanagementmenuroledisplay/'
                                },
                            ]
                        },
                        {
                            'name': '权限管理',
                            'codename': 'account_management_A2',
                            'models': [
                                {
                                    'name': '权限管理',
                                    'codename': 'ProvenanceSystemSettingsAccountManagementAuthority',
                                    'url': f'/{ADMIN_URL_ZDY}account_management/provenancesystemsettingsaccountmanagementauthority/'
                                },
                                {
                                    'name': '菜单权限',
                                    'codename': 'ProvenanceSystemSettingsMenuManagementMenuPermission',
                                    'url': f'/{ADMIN_URL_ZDY}menu_management/provenancesystemsettingsmenumanagementmenupermission/'
                                },
                                {
                                    'name': '菜单展示权限',
                                    'codename': 'ProvenanceSystemSettingsAccountManagementPermissionMenuDisplay',
                                    'url': f'/{ADMIN_URL_ZDY}account_management/provenancesystemsettingsaccountmanagementpermissionmenudisplay/'
                                }
                                # {
                                #     'name': '权限结果',
                                #     'codename': 'ProvenanceSystemSettingsAccountManagementPermissionResults',
                                #     'url': f'/{ADMIN_URL_ZDY}account_management/provenancesystemsettingsaccountmanagementpermissionresults/'
                                # },
                                # {
                                #     'name': '认证授权',
                                #     'codename': 'auth',
                                #     'url': f'/{ADMIN_URL_ZDY}auth/group/'
                                # }
                            ]
                        }
                    ]
                },
                {
                    'name': '系统功能',
                    'codename': 'system_function',
                    'models': [
                        {
                            'name': '日常记录',
                            'codename': 'daily_records',
                            'models': [
                                {
                                    'name': '事件记录',
                                    'codename': 'ProvenanceSystemFunctionDailyRecordsEvent',
                                    'url': f'/{ADMIN_URL_ZDY}daily_records/provenancesystemfunctiondailyrecordsevent/'
                                },
                                {
                                    'name': '事件类型',
                                    'codename': 'ProvenanceSystemFunctionDailyRecordsEventType',
                                    'url': f'/{ADMIN_URL_ZDY}daily_records/provenancesystemfunctiondailyrecordseventtype/'
                                },
                                {
                                    'name': '日记本',
                                    'codename': 'ProvenanceSystemFunctionDailyRecordsDiary',
                                    'url': f'/{ADMIN_URL_ZDY}daily_records/provenancesystemfunctiondailyrecordsdiary/'
                                }
                            ]
                        },
                        {
                            'name': '密码管理',
                            'codename': 'password_records',
                            'models': [
                                {
                                    'name': '人员密码',
                                    'codename': 'ProvenanceSystemFunctionPasswordRecords',
                                    'url': f'/{ADMIN_URL_ZDY}password_records/provenancesystemfunctionpasswordrecords/'
                                },
                                {
                                    'name': '产品账户关联',
                                    'codename': 'ProvenanceSystemFunctionPasswordCorrelation',
                                    'url': f'/{ADMIN_URL_ZDY}password_records/provenancesystemfunctionpasswordcorrelation/'
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            'name': '学术域',
            'icon': 'fa fa-file',
            'codename': 'learning',
            'models': [
                {
                    'name': '自然科学',
                    'codename': 'natural_science',
                    'models': [
                        {
                            'name': '生物学',
                            'codename': 'biology',
                            'models': [
                                {
                                    'name': '生物学分类',
                                    'codename': 'biology',
                                    'url': f'/{ADMIN_URL_ZDY}biology/learningnaturalsciencebiologicalspecies/'
                                }
                            ]
                        },
                        {
                            'name': '天文学',
                            'codename': 'astronomy',
                            'models': [
                                {
                                    'name': '宇宙学',
                                    'codename': 'cosmology',
                                    'models': [
                                        {
                                            'name': '宇宙天体分类',
                                            'codename': 'LearningNaturalScienceAstronomyCosmologyCode',
                                            'url': f'/{ADMIN_URL_ZDY}cosmology/learningnaturalscienceastronomycosmologycode/'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            'name': '业务域',
            'icon': 'fa fa-file',
            'codename': 'learning',
            'models': [
                {
                    'name': '地理与政治',
                    'codename': 'geography_politics',
                    'models': [
                        {
                            'name': '国家与地区',
                            'codename': 'country',
                            'models': [
                                {
                                    'name': '国家与地区',
                                    'codename': 'TransactionGeographyPoliticsCountryCollect',
                                    'url': f'/{ADMIN_URL_ZDY}country/transactiongeographypoliticscountrycollect/'
                                },
                                {
                                    'name': '国家货币',
                                    'codename': 'TransactionGeographyPoliticsCountryCurrency',
                                    'url': f'/{ADMIN_URL_ZDY}country/transactiongeographypoliticscountrycurrency/'
                                }
                            ]
                        },
                        {
                            'name': '行政区划分',
                            'codename': 'district',
                            'models': [
                                {
                                    'name': '城镇信息',
                                    'codename': 'TransactionGeographyPoliticsDistrictBasic',
                                    'url': f'/{ADMIN_URL_ZDY}district/transactiongeographypoliticsdistrictbasic/'
                                }
                            ]
                        }
                    ]
                },
                {
                    'name': '社会与文化',
                    'codename': 'social_culture',
                    'models': [
                        {
                            'name': '民族人口',
                            'codename': 'ethnic_population',
                            'models': [
                                {
                                    'name': '个人信息',
                                    'codename': 'personal_Information',
                                    'models': [
                                        {
                                            'name': '个人信息',
                                            'codename': 'TransactionSocialCultureEthnicPopulationPersonalInformationPerson',
                                            'url': f'/{ADMIN_URL_ZDY}personal_Information/transactionsocialcultureethnicpopulationpersonalinformationperson/'
                                        },
                                        {
                                            'name': '个人国家信息',
                                            'codename': 'TransactionSocialCultureEthnicPopulationPersonalInformationPersonCountry',
                                            'url': f'/{ADMIN_URL_ZDY}personal_Information/transactionsocialcultureethnicpopulationpersonalinformationpersoncountry/'
                                        },
                                        {
                                            'name': '个人生日信息',
                                            'codename': 'TransactionSocialCultureEthnicPopulationPersonalInformationPersonBirthday',
                                            'url': f'/{ADMIN_URL_ZDY}personal_Information/transactionsocialcultureethnicpopulationpersonalinformationpersonbirthday/'
                                        },
                                        {
                                            'name': '个人地址信息',
                                            'codename': 'TransactionSocialCultureEthnicPopulationPersonalInformationPersonAddress',
                                            'url': f'/{ADMIN_URL_ZDY}personal_Information/transactionsocialcultureethnicpopulationpersonalinformationpersonaddress/'
                                        },
                                        {
                                            'name': '个人事件记录',
                                            'codename': 'TransactionSocialCultureEthnicPopulationPersonalInformationPersonEvent',
                                            'url': f'/{ADMIN_URL_ZDY}personal_Information/transactionsocialcultureethnicpopulationpersonalinformationpersonevent/'
                                        },
                                        {
                                            'name': '个人所属民族',
                                            'codename': 'TransactionSocialCultureEthnicPopulationPersonalInformationPersonNation',
                                            'url': f'/{ADMIN_URL_ZDY}personal_Information/transactionsocialcultureethnicpopulationpersonalinformationpersonnation/'
                                        },
                                        {
                                            'name': '个人联系信息',
                                            'codename': 'TransactionSocialCultureEthnicPopulationPersonalInformationPersonConnections',
                                            'url': f'/{ADMIN_URL_ZDY}personal_Information/transactionsocialcultureethnicpopulationpersonalinformationpersonconnections/'
                                        },
                                        {
                                            'name': '人员证件信息',
                                            'codename': 'TransactionSocialCultureEthnicPopulationPersonalInformationPersonCertificate',
                                            'url': f'/{ADMIN_URL_ZDY}personal_Information/transactionsocialcultureethnicpopulationpersonalinformationpersoncertificate/'
                                        }
                                    ]
                                },
                                {
                                    'name': '民族分类与特征',
                                    'codename': 'ethnic_classification_characteristics',
                                    'models': [
                                        {
                                            'name': '民族基本信息',
                                            'codename': 'TransactionSocialCultureEthnicPopulationEthnicClassificationCharacteristicsBrief',
                                            'url': f'/{ADMIN_URL_ZDY}ethnic_classification_characteristics/transactionsocialcultureethnicpopulationethnicclassificationcharacteristicsbrief/'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    'name': '经济与产业',
                    'codename': 'economy_industry',
                    'models': [
                        {
                            'name': '企业与组织',
                            'codename': 'organizations',
                            'models': [
                                {
                                    'name': '组织基本描述',
                                    'codename': 'TransactionEconomyIndustryOrganizationsBases',
                                    'url': f'/{ADMIN_URL_ZDY}organizations/transactioneconomyindustryorganizationsbases/'
                                },
                                {
                                    'name': '组织称呼信息',
                                    'codename': 'TransactionEconomyIndustryOrganizationsCall',
                                    'url': f'/{ADMIN_URL_ZDY}organizations/transactioneconomyindustryorganizationscall/'
                                },
                                {
                                    'name': '组织地址信息',
                                    'codename': 'TransactionEconomyIndustryOrganizationsAddress',
                                    'url': f'/{ADMIN_URL_ZDY}organizations/transactioneconomyindustryorganizationsaddress/'
                                },
                                {
                                    'name': '组织证件信息',
                                    'codename': 'TransactionEconomyIndustryOrganizationsCertificate',
                                    'url': f'/{ADMIN_URL_ZDY}organizations/transactioneconomyindustryorganizationscertificate/'
                                },
                                {
                                    'name': '组织联系方式',
                                    'codename': 'TransactionEconomyIndustryOrganizationsContact',
                                    'url': f'/{ADMIN_URL_ZDY}organizations/transactioneconomyindustryorganizationscontact/'
                                },
                                {
                                    'name': '组织详情描述',
                                    'codename': 'TransactionEconomyIndustryOrganizationsDetails',
                                    'url': f'/{ADMIN_URL_ZDY}organizations/transactioneconomyindustryorganizationsdetails/'
                                }
                            ]
                        },
                        {
                            'name': '产品与服务',
                            'codename': 'products',
                            'models': [
                                {
                                    'name': '产品基本信息',
                                    'codename': 'TransactionEconomyIndustryProductsBasis',
                                    'url': f'/{ADMIN_URL_ZDY}products/transactioneconomyindustryproductsbasis/'
                                },
                                {
                                    'name': '产品所属组织',
                                    'codename': 'TransactionEconomyIndustryProductsAffiliation',
                                    'url': f'/{ADMIN_URL_ZDY}products/transactioneconomyindustryproductsaffiliation/'
                                },
                                {
                                    'name': '产品类别',
                                    'codename': 'TransactionEconomyIndustryProductsType',
                                    'url': f'/{ADMIN_URL_ZDY}products/transactioneconomyindustryproductstype/'
                                },
                                {
                                    'name': '产品称呼信息',
                                    'codename': 'TransactionEconomyIndustryProductsCall',
                                    'url': f'/{ADMIN_URL_ZDY}products/transactioneconomyindustryproductscall/'
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]
}
MEDITOR_DEFAULT_CONFIG = MEDITOR_DEFAULT_CONFIG
UEDITOR_DEFAULT_CONFIG = UEDITOR_DEFAULT_CONFIG
