# Generated by Django 4.1 on 2023-06-02 18:12

from django.db import migrations, models
import django.db.models.deletion
import simplepro.components.fields
import simplepro.editor.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("country", "0001_initial"),
        ("standard_encoding", "0001_initial"),
        ("organizations", "0002_initial"),
        ("products", "0001_initial"),
        ("ethnic_classification_characteristics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionSocialCultureEthnicPopulationPersonalInformationPerson",
            fields=[
                (
                    "ID",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="标识",
                    ),
                ),
                (
                    "CREATE_TIME",
                    simplepro.components.fields.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "UPDATE_TIME",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "STATUS_IS_DELETE",
                    models.BooleanField(default=False, verbose_name="逻辑删除"),
                ),
                (
                    "STATUS_IS_EFFECTIVE",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "SURNAME",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=100, null=True, verbose_name="姓"
                    ),
                ),
                (
                    "NAME",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=100, null=True, verbose_name="名称"
                    ),
                ),
                (
                    "DATE_OF_DEATH",
                    simplepro.components.fields.DateField(
                        blank=True,
                        default="2023-06-02 18:12:26",
                        null=True,
                        verbose_name="出生日期",
                    ),
                ),
                (
                    "DETAIL",
                    simplepro.editor.fields.MDTextField(
                        blank=True, default=None, null=True, verbose_name="简介"
                    ),
                ),
                (
                    "SEX",
                    simplepro.components.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="standard_encoding.provenancesystemsettingsstandardcodemaindict",
                        verbose_name="生理性别",
                    ),
                ),
            ],
            options={
                "verbose_name": "个人信息",
                "verbose_name_plural": "个人信息",
                "db_table": "TransactionSocialCultureEthnicPopulationPersonalInformationPerson",
                "ordering": ["-CREATE_TIME"],
            },
        ),
        migrations.CreateModel(
            name="TransactionSocialCultureEthnicPopulationPersonalInformationPersonEvent",
            fields=[
                (
                    "ID",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="标识",
                    ),
                ),
                (
                    "CREATE_TIME",
                    simplepro.components.fields.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "UPDATE_TIME",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "STATUS_IS_DELETE",
                    models.BooleanField(default=False, verbose_name="逻辑删除"),
                ),
                (
                    "STATUS_IS_EFFECTIVE",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "DATE",
                    simplepro.components.fields.DateField(
                        blank=True,
                        default="2023-06-02 18:12:26",
                        null=True,
                        verbose_name="发生日期",
                    ),
                ),
                (
                    "DETAIL",
                    simplepro.editor.fields.MDTextField(
                        blank=True, default=None, null=True, verbose_name="正文"
                    ),
                ),
                (
                    "ID_PERSON",
                    simplepro.components.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personal_Information.transactionsocialcultureethnicpopulationpersonalinformationperson",
                        verbose_name="个人",
                    ),
                ),
                (
                    "RTYPE_EVENT",
                    simplepro.components.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="事件类型",
                        to="standard_encoding.provenancesystemsettingsstandardcodemaindict",
                        verbose_name="事件类型",
                    ),
                ),
            ],
            options={
                "verbose_name": "人员事件记录",
                "verbose_name_plural": "人员事件记录",
                "db_table": "TransactionSocialCultureEthnicPopulationPersonalInformationPersonEvent",
                "ordering": ["-DATE"],
            },
        ),
        migrations.CreateModel(
            name="TransactionSocialCultureEthnicPopulationPersonalInformationPersonCountry",
            fields=[
                (
                    "ID",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="标识",
                    ),
                ),
                (
                    "CREATE_TIME",
                    simplepro.components.fields.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "UPDATE_TIME",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "STATUS_IS_DELETE",
                    models.BooleanField(default=False, verbose_name="逻辑删除"),
                ),
                (
                    "STATUS_IS_EFFECTIVE",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "DATE_OF_DEATH",
                    simplepro.components.fields.DateField(
                        blank=True,
                        default="2023-06-02 18:12:26",
                        null=True,
                        verbose_name="加入时间",
                    ),
                ),
                (
                    "ID_NATION",
                    simplepro.components.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="country.transactiongeographypoliticscountrycollect",
                        verbose_name="国籍",
                    ),
                ),
                (
                    "ID_PERSON",
                    simplepro.components.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personal_Information.transactionsocialcultureethnicpopulationpersonalinformationperson",
                        verbose_name="个人",
                    ),
                ),
            ],
            options={
                "verbose_name": "个人国家信息",
                "verbose_name_plural": "个人国家信息",
                "db_table": "TransactionSocialCultureEthnicPopulationPersonalInformationPersonCountry",
                "ordering": ["-CREATE_TIME"],
            },
        ),
        migrations.CreateModel(
            name="TransactionSocialCultureEthnicPopulationPersonalInformationPersonConnections",
            fields=[
                (
                    "ID",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="标识",
                    ),
                ),
                (
                    "CREATE_TIME",
                    simplepro.components.fields.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "UPDATE_TIME",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "STATUS_IS_DELETE",
                    models.BooleanField(default=False, verbose_name="逻辑删除"),
                ),
                (
                    "STATUS_IS_EFFECTIVE",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "NUMBER",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=255, null=True, verbose_name="账号"
                    ),
                ),
                (
                    "ID_PERSON",
                    simplepro.components.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personal_Information.transactionsocialcultureethnicpopulationpersonalinformationperson",
                        verbose_name="个人",
                    ),
                ),
                (
                    "ID_PRODUCTS",
                    simplepro.components.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.transactioneconomyindustryproductsbasis",
                        verbose_name="产品",
                    ),
                ),
            ],
            options={
                "verbose_name": "人员联系信息",
                "verbose_name_plural": "人员联系信息",
                "db_table": "TransactionSocialCultureEthnicPopulationPersonalInformationPersonConnections",
                "ordering": ["-CREATE_TIME"],
            },
        ),
        migrations.CreateModel(
            name="TransactionSocialCultureEthnicPopulationPersonalInformationPersonCertificate",
            fields=[
                (
                    "ID",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="标识",
                    ),
                ),
                (
                    "CREATE_TIME",
                    simplepro.components.fields.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "UPDATE_TIME",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "STATUS_IS_DELETE",
                    models.BooleanField(default=False, verbose_name="逻辑删除"),
                ),
                (
                    "STATUS_IS_EFFECTIVE",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "NUMBER",
                    simplepro.components.fields.CharField(
                        blank=True,
                        help_text="证件号",
                        max_length=255,
                        null=True,
                        verbose_name="证件号",
                    ),
                ),
                (
                    "DATE_ISSUED",
                    simplepro.components.fields.DateField(
                        blank=True,
                        default="2023-06-02 18:12:26",
                        null=True,
                        verbose_name="证件签发日期",
                    ),
                ),
                (
                    "DATE_START",
                    simplepro.components.fields.DateField(
                        blank=True,
                        default="2023-06-02 18:12:26",
                        null=True,
                        verbose_name="证件有效开始日期",
                    ),
                ),
                (
                    "DATE_END",
                    simplepro.components.fields.DateField(
                        blank=True,
                        default="2023-06-02 18:12:26",
                        null=True,
                        verbose_name="证件有效结束日期",
                    ),
                ),
                (
                    "CODE",
                    simplepro.components.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="standard_encoding.provenancesystemsettingsstandardcodemaindict",
                        verbose_name="个人证件类别",
                    ),
                ),
                (
                    "ID_ORGANIZATIONS",
                    simplepro.components.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="证件签发组织",
                        to="organizations.transactioneconomyindustryorganizationsbases",
                        verbose_name="证件签发组织",
                    ),
                ),
                (
                    "ID_PERSON",
                    simplepro.components.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personal_Information.transactionsocialcultureethnicpopulationpersonalinformationperson",
                        verbose_name="个人",
                    ),
                ),
            ],
            options={
                "verbose_name": "人员证件信息",
                "verbose_name_plural": "人员证件信息",
                "db_table": "TransactionSocialCultureEthnicPopulationPersonalInformationPersonCertificate",
                "ordering": ["-CREATE_TIME"],
            },
        ),
        migrations.CreateModel(
            name="TransactionSocialCultureEthnicPopulationPersonalInformationPersonBirthday",
            fields=[
                (
                    "ID",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="标识",
                    ),
                ),
                (
                    "CREATE_TIME",
                    simplepro.components.fields.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "UPDATE_TIME",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "STATUS_IS_DELETE",
                    models.BooleanField(default=False, verbose_name="逻辑删除"),
                ),
                (
                    "STATUS_IS_EFFECTIVE",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "DATE_START",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=4, null=True, verbose_name="生日"
                    ),
                ),
                (
                    "ID_PERSON",
                    simplepro.components.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personal_Information.transactionsocialcultureethnicpopulationpersonalinformationperson",
                        verbose_name="个人",
                    ),
                ),
                (
                    "TYPE_BIRTHDAY",
                    simplepro.components.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="standard_encoding.provenancesystemsettingsstandardcodemaindict",
                        verbose_name="生日类别",
                    ),
                ),
            ],
            options={
                "verbose_name": "个人生日信息",
                "verbose_name_plural": "个人生日信息",
                "db_table": "TransactionSocialCultureEthnicPopulationPersonalInformationPersonBirthday",
                "ordering": ["-CREATE_TIME"],
            },
        ),
        migrations.CreateModel(
            name="TransactionSocialCultureEthnicPopulationPersonalInformationPersonAddress",
            fields=[
                (
                    "ID",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="标识",
                    ),
                ),
                (
                    "CREATE_TIME",
                    simplepro.components.fields.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "UPDATE_TIME",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "STATUS_IS_DELETE",
                    models.BooleanField(default=False, verbose_name="逻辑删除"),
                ),
                (
                    "STATUS_IS_EFFECTIVE",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "ADDRESS_TXT",
                    simplepro.components.fields.CharField(
                        blank=True,
                        help_text="输入地址",
                        max_length=255,
                        null=True,
                        verbose_name="地址",
                    ),
                ),
                (
                    "ID_PERSON",
                    simplepro.components.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personal_Information.transactionsocialcultureethnicpopulationpersonalinformationperson",
                        verbose_name="个人",
                    ),
                ),
                (
                    "TYPE_ADDRESS",
                    simplepro.components.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="standard_encoding.provenancesystemsettingsstandardcodemaindict",
                        verbose_name="地址类别",
                    ),
                ),
            ],
            options={
                "verbose_name": "人员地址信息",
                "verbose_name_plural": "人员地址信息",
                "db_table": "TransactionSocialCultureEthnicPopulationPersonalInformationPersonAddress",
                "ordering": ["-CREATE_TIME"],
            },
        ),
        migrations.CreateModel(
            name="TransactionSocialCultureEthnicPopulationPersonalInformationPersonNation",
            fields=[
                (
                    "ID",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="标识",
                    ),
                ),
                (
                    "CREATE_TIME",
                    simplepro.components.fields.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "UPDATE_TIME",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "STATUS_IS_DELETE",
                    models.BooleanField(default=False, verbose_name="逻辑删除"),
                ),
                (
                    "STATUS_IS_EFFECTIVE",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "ID_NATION",
                    simplepro.components.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ethnic_classification_characteristics.transactionsocialcultureethnicpopulationethnicclassificationcharacteristicsbrief",
                        verbose_name="民族",
                    ),
                ),
                (
                    "ID_PERSON",
                    simplepro.components.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personal_Information.transactionsocialcultureethnicpopulationpersonalinformationperson",
                        verbose_name="个人",
                    ),
                ),
            ],
            options={
                "verbose_name": "个人所属民族",
                "verbose_name_plural": "个人所属民族",
                "db_table": "TransactionSocialCultureEthnicPopulationPersonalInformationPersonNation",
                "ordering": ["-CREATE_TIME"],
                "unique_together": {("ID_PERSON", "ID_NATION")},
            },
        ),
    ]
