# Generated by Django 4.1 on 2023-06-02 20:16

from django.db import migrations
import simplepro.components.fields


class Migration(migrations.Migration):

    dependencies = [
        ("personal_Information", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionsocialcultureethnicpopulationpersonalinformationperson",
            name="DATE_OF_DEATH",
            field=simplepro.components.fields.DateField(
                blank=True,
                default="2023-06-02 20:16:02",
                null=True,
                verbose_name="出生日期",
            ),
        ),
        migrations.AlterField(
            model_name="transactionsocialcultureethnicpopulationpersonalinformationpersoncertificate",
            name="DATE_END",
            field=simplepro.components.fields.DateField(
                blank=True,
                default="2023-06-02 20:16:02",
                null=True,
                verbose_name="证件有效结束日期",
            ),
        ),
        migrations.AlterField(
            model_name="transactionsocialcultureethnicpopulationpersonalinformationpersoncertificate",
            name="DATE_ISSUED",
            field=simplepro.components.fields.DateField(
                blank=True,
                default="2023-06-02 20:16:02",
                null=True,
                verbose_name="证件签发日期",
            ),
        ),
        migrations.AlterField(
            model_name="transactionsocialcultureethnicpopulationpersonalinformationpersoncertificate",
            name="DATE_START",
            field=simplepro.components.fields.DateField(
                blank=True,
                default="2023-06-02 20:16:02",
                null=True,
                verbose_name="证件有效开始日期",
            ),
        ),
        migrations.AlterField(
            model_name="transactionsocialcultureethnicpopulationpersonalinformationpersoncountry",
            name="DATE_OF_DEATH",
            field=simplepro.components.fields.DateField(
                blank=True,
                default="2023-06-02 20:16:02",
                null=True,
                verbose_name="加入时间",
            ),
        ),
        migrations.AlterField(
            model_name="transactionsocialcultureethnicpopulationpersonalinformationpersonevent",
            name="DATE",
            field=simplepro.components.fields.DateField(
                blank=True,
                default="2023-06-02 20:16:02",
                null=True,
                verbose_name="发生日期",
            ),
        ),
    ]
