# Generated by Django 4.1 on 2023-06-07 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account_management", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="provenancesystemsettingsaccountmanagementsuper",
            old_name="ID",
            new_name="id",
        ),
    ]
