# Generated by Django 4.1 on 2023-06-12 15:30

from django.db import migrations
import django.db.models.deletion
import simplepro.components.fields


class Migration(migrations.Migration):

    dependencies = [
        (
            "account_management",
            "0004_alter_provenancesystemsettingsaccountmanagementpermissionresults_id_authority_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="provenancesystemsettingsaccountmanagementauthority",
            name="ID_PARENT",
            field=simplepro.components.fields.TreeComboboxField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account_management.provenancesystemsettingsaccountmanagementauthority",
                verbose_name="上级",
            ),
        ),
        migrations.AlterField(
            model_name="provenancesystemsettingsaccountmanagementsubscribergroup",
            name="NAME",
            field=simplepro.components.fields.CharField(
                blank=True, max_length=255, null=True, unique=True, verbose_name="组名"
            ),
        ),
    ]
