# Generated by Django 4.1 on 2023-06-12 16:50

from django.db import migrations, models
import django.db.models.deletion
import simplepro.components.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        (
            "account_management",
            "0005_alter_provenancesystemsettingsaccountmanagementauthority_id_parent_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="provenancesystemsettingsaccountmanagementsubscribergroup",
            options={
                "ordering": ["-CREATE_TIME"],
                "verbose_name": "用户组",
                "verbose_name_plural": "用户组",
            },
        ),
        migrations.RemoveField(
            model_name="provenancesystemsettingsaccountmanagementsubscribergroup",
            name="ID_SUBSCRIBER",
        ),
        migrations.CreateModel(
            name="ProvenanceSystemSettingsAccountManagementSubscriberGroupAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "CREATE_TIME",
                    simplepro.components.fields.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "UPDATE_TIME",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "STATUS_IS_DELETE",
                    models.BooleanField(default=False, verbose_name="逻辑删除"),
                ),
                (
                    "STATUS_IS_EFFECTIVE",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "ID_SUBSCRIBER",
                    simplepro.components.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account_management.provenancesystemsettingsaccountmanagementsubscriber",
                        verbose_name="订阅用户",
                    ),
                ),
                (
                    "ID_SUBSCRIBER_GROUP",
                    simplepro.components.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account_management.provenancesystemsettingsaccountmanagementsubscribergroup",
                        verbose_name="用户组",
                    ),
                ),
            ],
            options={
                "verbose_name": "订阅用户组",
                "verbose_name_plural": "订阅用户组",
                "db_table": "ProvenanceSystemSettingsAccountManagementSubscriberGroupAccount",
                "ordering": ["-CREATE_TIME"],
            },
        ),
        migrations.CreateModel(
            name="ProvenanceSystemSettingsAccountManagementRoleSubscriberGroup",
            fields=[
                (
                    "ID",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="标识",
                    ),
                ),
                (
                    "CREATE_TIME",
                    simplepro.components.fields.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "UPDATE_TIME",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "STATUS_IS_DELETE",
                    models.BooleanField(default=False, verbose_name="逻辑删除"),
                ),
                (
                    "STATUS_IS_EFFECTIVE",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "ID_ROLE",
                    simplepro.components.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account_management.provenancesystemsettingsaccountmanagementrole",
                        verbose_name="角色",
                    ),
                ),
                (
                    "ID_SUBSCRIBER_GROUP",
                    simplepro.components.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account_management.provenancesystemsettingsaccountmanagementsubscribergroup",
                        verbose_name="用户组",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户组角色",
                "verbose_name_plural": "用户组角色",
                "db_table": "ProvenanceSystemSettingsAccountManagementRoleSubscriberGroup",
                "ordering": ["-CREATE_TIME"],
            },
        ),
        migrations.CreateModel(
            name="ProvenanceSystemSettingsAccountManagementRoleSubscriber",
            fields=[
                (
                    "ID",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="标识",
                    ),
                ),
                (
                    "CREATE_TIME",
                    simplepro.components.fields.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "UPDATE_TIME",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "STATUS_IS_DELETE",
                    models.BooleanField(default=False, verbose_name="逻辑删除"),
                ),
                (
                    "STATUS_IS_EFFECTIVE",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "ID_ROLE",
                    simplepro.components.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account_management.provenancesystemsettingsaccountmanagementrole",
                        verbose_name="角色",
                    ),
                ),
                (
                    "ID_SUBSCRIBER",
                    simplepro.components.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account_management.provenancesystemsettingsaccountmanagementsubscriber",
                        verbose_name="订阅用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户角色",
                "verbose_name_plural": "用户角色",
                "db_table": "ProvenanceSystemSettingsAccountManagementRoleSubscriber",
                "ordering": ["-CREATE_TIME"],
            },
        ),
    ]
