# Generated by Django 4.1 on 2023-06-26 16:21

from django.db import migrations
import django.db.models.deletion
import simplepro.components.fields


class Migration(migrations.Migration):

    dependencies = [
        ("standard_encoding", "0001_initial"),
        (
            "account_management",
            "0006_alter_provenancesystemsettingsaccountmanagementsubscribergroup_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="provenancesystemsettingsaccountmanagementauthority",
            name="CODE",
            field=simplepro.components.fields.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="standard_encoding.provenancesystemsettingsstandardcodemaindict",
                verbose_name="产品关联类别",
            ),
        ),
    ]
