# Generated by Django 4.1 on 2023-06-28 13:03

from django.db import migrations, models
import django.db.models.deletion
import simplepro.components.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("standard_encoding", "0001_initial"),
        (
            "account_management",
            "0007_provenancesystemsettingsaccountmanagementauthority_code",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="provenancesystemsettingsaccountmanagementauthority",
            name="CODE",
            field=simplepro.components.fields.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="standard_encoding.provenancesystemsettingsstandardcodemaindict",
                verbose_name="权限类别",
            ),
        ),
        migrations.CreateModel(
            name="ProvenanceSystemSettingsAccountManagementPermissionMenuDisplay",
            fields=[
                (
                    "ID",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="标识",
                    ),
                ),
                (
                    "CREATE_TIME",
                    simplepro.components.fields.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "UPDATE_TIME",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "STATUS_IS_DELETE",
                    models.BooleanField(default=False, verbose_name="逻辑删除"),
                ),
                (
                    "STATUS_IS_EFFECTIVE",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "ID_AUTHORITY",
                    simplepro.components.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account_management.provenancesystemsettingsaccountmanagementauthority",
                        verbose_name="权限",
                    ),
                ),
            ],
            options={
                "verbose_name": "菜单展示",
                "verbose_name_plural": "菜单展示",
                "db_table": "ProvenanceSystemSettingsAccountManagementPermissionMenuDisplay",
                "ordering": ["-CREATE_TIME"],
            },
        ),
    ]
