# Generated by Django 4.1 on 2023-06-28 13:03

from django.db import migrations
import django.db.models.deletion
import simplepro.components.fields


class Migration(migrations.Migration):

    dependencies = [
        (
            "menu_management",
            "0004_alter_provenancesystemsettingsmenumanagementmenu_unique_together_and_more",
        ),
        (
            "account_management",
            "0008_alter_provenancesystemsettingsaccountmanagementauthority_code_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="provenancesystemsettingsaccountmanagementpermissionmenudisplay",
            name="ID_DISPLAY",
            field=simplepro.components.fields.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="menu_management.provenancesystemsettingsmenumanagementmenuroledisplay",
                verbose_name="展示菜单",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="provenancesystemsettingsaccountmanagementpermissionmenudisplay",
            unique_together={("ID_DISPLAY", "ID_AUTHORITY")},
        ),
    ]
