# Generated by Django 4.1 on 2023-06-12 16:18

from django.db import migrations, models
import django.db.models.deletion
import simplepro.components.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "account_management",
            "0005_alter_provenancesystemsettingsaccountmanagementauthority_id_parent_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ProvenanceSystemSettingsMenuManagementMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "CREATE_TIME",
                    simplepro.components.fields.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "UPDATE_TIME",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "STATUS_IS_DELETE",
                    models.BooleanField(default=False, verbose_name="逻辑删除"),
                ),
                (
                    "STATUS_IS_EFFECTIVE",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "NAME",
                    simplepro.components.fields.CharField(
                        max_length=255, verbose_name="中文描述"
                    ),
                ),
                (
                    "ID_PARENT",
                    simplepro.components.fields.TreeComboboxField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="menu_management.provenancesystemsettingsmenumanagementmenu",
                        verbose_name="上级",
                    ),
                ),
            ],
            options={
                "verbose_name": "菜单管理",
                "verbose_name_plural": "菜单管理",
                "db_table": "ProvenanceSystemSettingsMenuManagementMenu",
                "ordering": ["-CREATE_TIME"],
            },
        ),
        migrations.CreateModel(
            name="ProvenanceSystemSettingsMenuManagementMenuPermission",
            fields=[
                (
                    "ID",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="标识",
                    ),
                ),
                (
                    "CREATE_TIME",
                    simplepro.components.fields.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "UPDATE_TIME",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "STATUS_IS_DELETE",
                    models.BooleanField(default=False, verbose_name="逻辑删除"),
                ),
                (
                    "STATUS_IS_EFFECTIVE",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "ID_AUTHORITY",
                    simplepro.components.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account_management.provenancesystemsettingsaccountmanagementauthority",
                        verbose_name="权限",
                    ),
                ),
                (
                    "ID_MENU",
                    simplepro.components.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="menu_management.provenancesystemsettingsmenumanagementmenu",
                        verbose_name="菜单",
                    ),
                ),
            ],
            options={
                "verbose_name": "菜单权限",
                "verbose_name_plural": "菜单权限",
                "db_table": "ProvenanceSystemSettingsMenuManagementMenuPermission",
                "ordering": ["-CREATE_TIME"],
                "unique_together": {("ID_MENU", "ID_AUTHORITY")},
            },
        ),
    ]
