# Generated by Django 4.1 on 2023-06-28 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "account_management",
            "0009_provenancesystemsettingsaccountmanagementpermissionmenudisplay_id_display_and_more",
        ),
        (
            "menu_management",
            "0004_alter_provenancesystemsettingsmenumanagementmenu_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="provenancesystemsettingsmenumanagementmenuroledisplay",
            unique_together={("ID_ROLE", "ID_MENU")},
        ),
    ]
